export const GET_GNOMES_INFO = 'GET_GNOMES_INFO';
export const SET_SEARCH_BY_PARAMETER = 'SET_SEARCH_BY_PARAMETER';
export const FILTER_GNOMES_INFO = 'FILTER_GNOMES_INFO';
export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
